-- =============================================================================
-- AwardLens — initial schema
-- =============================================================================
--
-- This is the production equivalent of the file-backed store in
-- `src/lib/db/local.ts`. Column names are the snake_case form of the field
-- names in `src/lib/domain/types.ts`; enum values are copied verbatim from the
-- string unions in that file, so a mapping layer only has to change case.
--
-- Conventions used throughout:
--   * every id is a uuid generated by the database unless the domain requires
--     an externally supplied key (processed_stripe_events);
--   * every organisation-owned table carries `organization_id` even when the
--     value is derivable through a parent. That denormalisation is deliberate:
--     it lets the row-level security policies in 0002 decide ownership with a
--     single indexed predicate instead of a join, and it means a mistake in one
--     policy cannot leak a whole table through a parent's policy;
--   * `on delete cascade` follows the ownership chains
--     award -> document -> segment and obligation -> citation, so deleting an
--     award leaves nothing behind;
--   * references to `profiles` cascade when the row belongs to the user
--     (reminders, notification preferences, memberships) and restrict when the
--     row belongs to the organisation and merely records who created it
--     (organizations, awards, exports). Deleting an account therefore has to go
--     through the application's organisation-data deletion path rather than
--     silently orphaning or destroying an organisation's compliance record.
--     See supabase/README.md, "Deleting a user".
--
-- Safe to re-run: every object is created with `if not exists` or an equivalent
-- guard.
-- =============================================================================

create extension if not exists "pgcrypto" with schema extensions;

-- -----------------------------------------------------------------------------
-- Enums
--
-- Postgres has no `create type if not exists`, so each type is guarded. Values
-- are exactly the string unions in src/lib/domain/types.ts. Adding a value later
-- is `alter type ... add value`; removing one is a rewrite, so the sets below
-- should be treated as an API.
-- -----------------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_type where typname = 'obligation_category') then
    create type public.obligation_category as enum (
      'reporting',
      'financial',
      'deliverable',
      'performance_metric',
      'prior_approval',
      'allowable_cost',
      'restricted_use',
      'communications_branding',
      'procurement',
      'records_retention',
      'data_collection',
      'participant_eligibility',
      'insurance',
      'audit',
      'match_cost_share',
      'subrecipient_oversight',
      'closeout',
      'renewal_continuation',
      'general_compliance',
      'other'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'obligation_priority') then
    create type public.obligation_priority as enum ('critical', 'high', 'medium', 'low');
  end if;

  if not exists (select 1 from pg_type where typname = 'review_status') then
    create type public.review_status as enum (
      'needs_review',
      'confirmed',
      'needs_clarification',
      'not_applicable',
      'archived'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'interpretation_level') then
    create type public.interpretation_level as enum ('explicit', 'light_interpretation', 'uncertain');
  end if;

  if not exists (select 1 from pg_type where typname = 'source_status') then
    create type public.source_status as enum ('verified', 'partial', 'unverified');
  end if;

  if not exists (select 1 from pg_type where typname = 'locator_type') then
    create type public.locator_type as enum ('page', 'section', 'paragraph');
  end if;

  if not exists (select 1 from pg_type where typname = 'parser_status') then
    create type public.parser_status as enum (
      'pending',
      'parsed',
      'no_text_layer',
      'password_protected',
      'corrupted',
      'unsupported',
      'failed'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'processing_stage') then
    create type public.processing_stage as enum (
      'securing_document',
      'reading_document',
      'identifying_award',
      'finding_obligations',
      'checking_sources',
      'preparing_review'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'processing_status') then
    create type public.processing_status as enum ('queued', 'running', 'succeeded', 'partial', 'failed');
  end if;

  if not exists (select 1 from pg_type where typname = 'award_status') then
    create type public.award_status as enum ('processing', 'active', 'failed', 'archived');
  end if;

  if not exists (select 1 from pg_type where typname = 'award_review_status') then
    create type public.award_review_status as enum ('not_started', 'in_progress', 'complete');
  end if;

  if not exists (select 1 from pg_type where typname = 'organization_role') then
    create type public.organization_role as enum ('owner', 'admin', 'member');
  end if;

  if not exists (select 1 from pg_type where typname = 'reminder_status') then
    create type public.reminder_status as enum ('scheduled', 'sent', 'skipped', 'failed', 'cancelled');
  end if;

  if not exists (select 1 from pg_type where typname = 'plan_id') then
    create type public.plan_id as enum ('demo', 'single_award', 'small_org', 'team');
  end if;

  if not exists (select 1 from pg_type where typname = 'export_format') then
    create type public.export_format as enum ('csv', 'ics', 'json', 'print');
  end if;

  -- The remaining string unions in types.ts. They are enums for the same reason
  -- as the ones above: an invalid value should be impossible to store, not
  -- merely unlikely.
  if not exists (select 1 from pg_type where typname = 'award_source_type') then
    create type public.award_source_type as enum ('pdf', 'docx', 'text', 'sample');
  end if;

  if not exists (select 1 from pg_type where typname = 'subscription_status') then
    create type public.subscription_status as enum (
      'active',
      'trialing',
      'past_due',
      'canceled',
      'incomplete'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'obligation_origin') then
    create type public.obligation_origin as enum ('extracted', 'manual', 'critic');
  end if;

  if not exists (select 1 from pg_type where typname = 'ask_answer_type') then
    create type public.ask_answer_type as enum ('answered', 'not_addressed', 'uncertain');
  end if;
end
$$;

-- -----------------------------------------------------------------------------
-- updated_at trigger
-- -----------------------------------------------------------------------------

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'Sets updated_at on every UPDATE. Attached to every table that has the column so the value cannot be forged or forgotten by a client.';

-- -----------------------------------------------------------------------------
-- profiles
--
-- One row per authenticated user, keyed by the Supabase auth user id. The app
-- never reads auth.users directly.
-- -----------------------------------------------------------------------------

create table if not exists public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  email       text not null,
  full_name   text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint profiles_email_lowercase check (email = lower(email)),
  constraint profiles_email_shape check (position('@' in email) > 1)
);

create unique index if not exists profiles_email_key on public.profiles (email);

comment on table public.profiles is 'Application-visible user record. id is the auth.users id; deleting the auth user deletes the profile.';

-- -----------------------------------------------------------------------------
-- organizations and membership
-- -----------------------------------------------------------------------------

create table if not exists public.organizations (
  id          uuid primary key default gen_random_uuid(),
  name        text not null check (length(btrim(name)) > 0),
  slug        text not null,
  created_by  uuid not null references public.profiles (id) on delete restrict,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create unique index if not exists organizations_slug_key on public.organizations (slug);

comment on column public.organizations.created_by is
  'Restricted rather than cascaded: deleting a user must not delete an organisation other people belong to. Account deletion runs the application organisation-data path first.';

create table if not exists public.organization_members (
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id         uuid not null references public.profiles (id) on delete cascade,
  role            public.organization_role not null default 'member',
  created_at      timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create index if not exists organization_members_user_id_idx
  on public.organization_members (user_id);

comment on table public.organization_members is
  'The single source of truth for authorisation. Every RLS policy in 0002 resolves to a lookup in this table.';

-- -----------------------------------------------------------------------------
-- awards
-- -----------------------------------------------------------------------------

create table if not exists public.awards (
  id                  uuid primary key default gen_random_uuid(),
  organization_id     uuid not null references public.organizations (id) on delete cascade,
  name                text not null check (length(btrim(name)) > 0),
  funder              text,
  recipient_name      text,
  award_number        text,
  award_amount        numeric(16, 2),
  currency            text not null default 'USD' check (currency ~ '^[A-Z]{3}$'),
  start_date          date,
  end_date            date,
  effective_date      date,
  grant_period_text   text,
  program_name        text,
  assistance_type     text,
  primary_contacts    jsonb not null default '[]'::jsonb,
  governing_documents jsonb not null default '[]'::jsonb,
  status              public.award_status not null default 'processing',
  review_status       public.award_review_status not null default 'not_started',
  source_type         public.award_source_type not null,
  created_by          uuid not null references public.profiles (id) on delete restrict,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint awards_primary_contacts_is_array check (jsonb_typeof(primary_contacts) = 'array'),
  constraint awards_governing_documents_is_array check (jsonb_typeof(governing_documents) = 'array')
);

comment on column public.awards.primary_contacts is 'AwardContact[] as stored by the extraction pipeline.';
comment on column public.awards.governing_documents is 'string[]: the documents the award incorporates by reference.';

-- -----------------------------------------------------------------------------
-- documents and segments
-- -----------------------------------------------------------------------------

create table if not exists public.documents (
  id                     uuid primary key default gen_random_uuid(),
  award_id               uuid not null references public.awards (id) on delete cascade,
  organization_id        uuid not null references public.organizations (id) on delete cascade,
  storage_path           text,
  original_filename      text not null,
  mime_type              text not null,
  byte_size              bigint not null check (byte_size >= 0),
  content_hash           text not null check (content_hash ~ '^[0-9a-f]{64}$'),
  parser_status          public.parser_status not null default 'pending',
  parser_message         text,
  page_count             integer check (page_count is null or page_count >= 0),
  extracted_text_version text not null default '1',
  created_at             timestamptz not null default now()
);

-- Duplicate detection: the same bytes uploaded twice inside one organisation is
-- the same document. Scoped to the organisation so one tenant cannot probe for
-- another tenant's documents by hash collision.
create unique index if not exists documents_organization_content_hash_key
  on public.documents (organization_id, content_hash);

create index if not exists documents_award_id_idx on public.documents (award_id);

comment on column public.documents.content_hash is 'SHA-256 of the raw bytes (see lib/documents/validation.ts hashContent).';
comment on column public.documents.storage_path is 'Object path inside the private award-documents bucket. Null until the bytes are stored.';

create table if not exists public.document_segments (
  id             uuid primary key default gen_random_uuid(),
  document_id    uuid not null references public.documents (id) on delete cascade,
  locator_type   public.locator_type not null,
  locator_value  text not null,
  heading        text,
  "text"         text not null,
  sequence       integer not null check (sequence >= 0),
  token_estimate integer not null default 0 check (token_estimate >= 0),
  created_at     timestamptz not null default now()
);

create unique index if not exists document_segments_document_sequence_key
  on public.document_segments (document_id, sequence);

create index if not exists document_segments_document_sequence_idx
  on public.document_segments (document_id, sequence);

comment on table public.document_segments is
  'Verbatim slices of a parsed document. No organization_id: ownership is resolved through documents, and 0002 enforces it with an EXISTS check.';

-- -----------------------------------------------------------------------------
-- processing runs
-- -----------------------------------------------------------------------------

create table if not exists public.processing_runs (
  id              uuid primary key default gen_random_uuid(),
  award_id        uuid not null references public.awards (id) on delete cascade,
  document_id     uuid not null references public.documents (id) on delete cascade,
  organization_id uuid not null references public.organizations (id) on delete cascade,
  status          public.processing_status not null default 'queued',
  stage           public.processing_stage not null default 'securing_document',
  model           text,
  prompt_version  text not null default '',
  started_at      timestamptz not null default now(),
  completed_at    timestamptz,
  error_code      text,
  error_message   text,
  usage_metadata  jsonb,
  created_at      timestamptz not null default now()
);

create index if not exists processing_runs_award_started_idx
  on public.processing_runs (award_id, started_at desc);

comment on column public.processing_runs.organization_id is
  'Denormalised from awards purely so RLS can authorise a run without joining. Not part of the ProcessingRun domain type.';
comment on column public.processing_runs.usage_metadata is 'UsageMetadata: token counts, call counts and per-stage timings. Nullable — a queued run has none.';

-- -----------------------------------------------------------------------------
-- obligations and citations
-- -----------------------------------------------------------------------------

create table if not exists public.obligations (
  id                     uuid primary key default gen_random_uuid(),
  award_id               uuid not null references public.awards (id) on delete cascade,
  organization_id        uuid not null references public.organizations (id) on delete cascade,
  category               public.obligation_category not null,
  title                  text not null check (length(btrim(title)) > 0),
  description            text not null,
  original_date_text     text,
  due_date               date,
  recurrence             text,
  internal_due_date      date,
  suggested_owner_role   text,
  assigned_user_id       uuid references public.profiles (id) on delete set null,
  priority               public.obligation_priority not null default 'medium',
  confidence             numeric not null check (confidence >= 0 and confidence <= 1),
  review_status          public.review_status not null default 'needs_review',
  interpretation_level   public.interpretation_level not null default 'explicit',
  consequence            text,
  clarification_question text,
  source_status          public.source_status not null default 'unverified',
  notes                  text,
  date_conflicts         jsonb not null default '[]'::jsonb,
  origin                 public.obligation_origin not null default 'extracted',
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  constraint obligations_date_conflicts_is_array check (jsonb_typeof(date_conflicts) = 'array')
);

create index if not exists obligations_award_id_idx on public.obligations (award_id);
create index if not exists obligations_org_due_date_idx on public.obligations (organization_id, due_date);
create index if not exists obligations_org_review_status_idx
  on public.obligations (organization_id, review_status);
create index if not exists obligations_assigned_user_idx
  on public.obligations (assigned_user_id)
  where assigned_user_id is not null;

comment on column public.obligations.confidence is 'Extraction confidence, 0-1. Constrained because a value outside that range would silently misrank the register.';
comment on column public.obligations.date_conflicts is 'DateConflict[]: competing dates the document states for the same obligation.';

create table if not exists public.obligation_citations (
  id                  uuid primary key default gen_random_uuid(),
  obligation_id       uuid not null references public.obligations (id) on delete cascade,
  document_segment_id uuid references public.document_segments (id) on delete set null,
  locator_type        public.locator_type not null,
  locator_value       text not null,
  excerpt             text not null,
  start_offset        integer check (start_offset is null or start_offset >= 0),
  end_offset          integer check (end_offset is null or end_offset >= 0),
  match_score         numeric not null default 0 check (match_score >= 0 and match_score <= 1),
  created_at          timestamptz not null default now()
);

create index if not exists obligation_citations_obligation_id_idx
  on public.obligation_citations (obligation_id);

comment on table public.obligation_citations is
  'Where an obligation came from. No organization_id: ownership is resolved through obligations, enforced with an EXISTS check in 0002.';
comment on column public.obligation_citations.document_segment_id is
  'Nullable and set null on delete: a citation whose segment is gone is still evidence of what the model quoted.';

-- -----------------------------------------------------------------------------
-- reminders
-- -----------------------------------------------------------------------------

create table if not exists public.reminders (
  id              uuid primary key default gen_random_uuid(),
  obligation_id   uuid not null references public.obligations (id) on delete cascade,
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id         uuid not null references public.profiles (id) on delete cascade,
  offset_days     integer not null check (offset_days >= 0),
  scheduled_for   timestamptz not null,
  sent_at         timestamptz,
  status          public.reminder_status not null default 'scheduled',
  idempotency_key text not null,
  last_error      text,
  created_at      timestamptz not null default now()
);

-- The send worker's safety net: a retried or double-scheduled cron run cannot
-- produce a second email for the same (obligation, user, offset).
create unique index if not exists reminders_idempotency_key_key
  on public.reminders (idempotency_key);

create index if not exists reminders_status_scheduled_for_idx
  on public.reminders (status, scheduled_for);

create index if not exists reminders_obligation_id_idx on public.reminders (obligation_id);

-- -----------------------------------------------------------------------------
-- subscriptions
-- -----------------------------------------------------------------------------

create table if not exists public.subscriptions (
  id                     uuid primary key default gen_random_uuid(),
  organization_id        uuid not null references public.organizations (id) on delete cascade,
  stripe_customer_id     text,
  stripe_subscription_id text,
  plan                   public.plan_id not null default 'demo',
  status                 public.subscription_status not null default 'active',
  period_end             timestamptz,
  award_credits          integer not null default 0 check (award_credits >= 0),
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now()
);

-- One subscription per organisation, matching upsertSubscription() in the local store.
create unique index if not exists subscriptions_organization_id_key
  on public.subscriptions (organization_id);

create unique index if not exists subscriptions_stripe_subscription_id_key
  on public.subscriptions (stripe_subscription_id)
  where stripe_subscription_id is not null;

create index if not exists subscriptions_stripe_customer_id_idx
  on public.subscriptions (stripe_customer_id)
  where stripe_customer_id is not null;

-- -----------------------------------------------------------------------------
-- exports
-- -----------------------------------------------------------------------------

create table if not exists public.exports (
  id              uuid primary key default gen_random_uuid(),
  award_id        uuid not null references public.awards (id) on delete cascade,
  organization_id uuid not null references public.organizations (id) on delete cascade,
  format          public.export_format not null,
  storage_path    text,
  generated_by    uuid not null references public.profiles (id) on delete restrict,
  generated_at    timestamptz not null default now()
);

create index if not exists exports_org_generated_at_idx
  on public.exports (organization_id, generated_at desc);

create index if not exists exports_award_id_idx on public.exports (award_id);

-- -----------------------------------------------------------------------------
-- audit events
-- -----------------------------------------------------------------------------

create table if not exists public.audit_events (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  user_id         uuid references public.profiles (id) on delete set null,
  event_type      text not null,
  entity_type     text not null,
  entity_id       text not null,
  metadata        jsonb not null default '{}'::jsonb,
  created_at      timestamptz not null default now(),
  constraint audit_events_metadata_is_object check (jsonb_typeof(metadata) = 'object')
);

create index if not exists audit_events_org_created_at_idx
  on public.audit_events (organization_id, created_at desc);

create index if not exists audit_events_entity_idx
  on public.audit_events (entity_type, entity_id);

comment on table public.audit_events is
  'Append-only. 0002 grants insert and select to members and no update or delete to anyone but the service role.';
comment on column public.audit_events.entity_id is 'Text, not uuid: some entities (storage objects, Stripe ids) are not uuids.';

-- -----------------------------------------------------------------------------
-- notification preferences
-- -----------------------------------------------------------------------------

create table if not exists public.notification_preferences (
  user_id         uuid not null references public.profiles (id) on delete cascade,
  organization_id uuid not null references public.organizations (id) on delete cascade,
  enabled         boolean not null default true,
  offsets         jsonb default '[30, 14, 7, 1]'::jsonb,
  updated_at      timestamptz not null default now(),
  primary key (user_id, organization_id),
  constraint notification_preferences_offsets_is_array
    check (offsets is null or jsonb_typeof(offsets) = 'array')
);

comment on column public.notification_preferences.offsets is
  'number[] of days before the due date. Null means "use the product default", which is what the application returns when no row exists.';

-- -----------------------------------------------------------------------------
-- ask exchanges
-- -----------------------------------------------------------------------------

create table if not exists public.ask_exchanges (
  id                        uuid primary key default gen_random_uuid(),
  award_id                  uuid not null references public.awards (id) on delete cascade,
  organization_id           uuid not null references public.organizations (id) on delete cascade,
  user_id                   uuid not null references public.profiles (id) on delete cascade,
  question                  text not null,
  answer                    text not null,
  answer_type               public.ask_answer_type not null,
  interpretation_level      public.interpretation_level not null default 'explicit',
  citations                 jsonb not null default '[]'::jsonb,
  suggested_funder_question text,
  created_at                timestamptz not null default now(),
  constraint ask_exchanges_citations_is_array check (jsonb_typeof(citations) = 'array')
);

create index if not exists ask_exchanges_award_created_at_idx
  on public.ask_exchanges (award_id, created_at);

comment on column public.ask_exchanges.citations is 'AskCitation[]: locator, excerpt and the segment id the answer was grounded in.';

-- -----------------------------------------------------------------------------
-- processed stripe events
--
-- Webhook idempotency. The primary key is Stripe's own event id, so a replayed
-- webhook loses the insert race instead of double-crediting an organisation.
-- Written only by the service role; see 0002.
-- -----------------------------------------------------------------------------

create table if not exists public.processed_stripe_events (
  id           text primary key,
  processed_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Performance indexes named in the product's read paths
-- -----------------------------------------------------------------------------

create index if not exists awards_org_created_at_idx
  on public.awards (organization_id, created_at desc);

create index if not exists awards_org_status_idx
  on public.awards (organization_id, status);

-- -----------------------------------------------------------------------------
-- updated_at triggers
-- -----------------------------------------------------------------------------

drop trigger if exists set_updated_at on public.profiles;
create trigger set_updated_at before update on public.profiles
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.organizations;
create trigger set_updated_at before update on public.organizations
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.awards;
create trigger set_updated_at before update on public.awards
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.obligations;
create trigger set_updated_at before update on public.obligations
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.subscriptions;
create trigger set_updated_at before update on public.subscriptions
  for each row execute function public.set_updated_at();

drop trigger if exists set_updated_at on public.notification_preferences;
create trigger set_updated_at before update on public.notification_preferences
  for each row execute function public.set_updated_at();
